export default {
  currentURL: document.getElementById("currentURL"),
  mainForm: document.getElementById("mainForm"),
  queryTableBody: document.getElementById("queryTableBody"),
  jsonTree: document.getElementById("jsonTree"),
  resStatus: document.getElementById("resStatus"),
  resSize: document.getElementById("resSize"),
  resTime: document.getElementById("resTime"),
  loginContainer: document.getElementById("loginContainer"),
  regForm: document.getElementById("regForm"),
  mainContent: document.getElementById("mainContent"),
  switchFormAction: document.getElementById("switchFormAction"),
  switchBtnQuestion: document.getElementById("switchBtnQuestion"),
  formTitle: document.getElementById("formTitle"),
  reqHistory: document.getElementById("reqHistory"),
  clearHistoryBtn: document.getElementById("clearHistoryBtn"),
  reqSettingsTitles: document.getElementById("reqSettingsTitles"),
  reqSettingsContent: document.getElementById("reqSettingsContent"),
  reqBody: document.getElementById("reqBody"),
};
